- id: fourmat
  name: fourmat
  description: "Fourmat: Batteries-included linting and autoformatting"
  entry: fourmat fix
  language: python
  language_version: python3
  require_serial: true # https://github.com/ambv/black/pull/675
  types: [python]
